wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1677521981.919318
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.9.7
      5: 0.13.8
      8:
      - 3
      - 5
architecture:
  desc: null
  value: MADDPG
batch_size:
  desc: null
  value: 128
env:
  desc: null
  value: Adaptable_street_rl
infra:
  desc: null
  value: Colab
learning_rate_actor:
  desc: null
  value: 0.001
learning_rate_critic:
  desc: null
  value: 0.001
