version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  win-test:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}
      - run:
          name: install dependencies
          command: |
            python --version
            pip install virtualenv
            virtualenv venv
            .\venv\Scripts\activate
            pip install .
            pip install .\test_lib\multiagent-particle-envs\
            pip install gym
            pip install mock pytest==6.0.0 pytest-cov==2.10.0 allure-pytest==2.8.16 pytest-html==1.22.1 pytest-repeat==0.8.0
      - save_cache:
          key: deps-{{ .Branch }}
          paths:
            - "venv"
      - run:
          name: make test directory
          command: mkdir test_results -Force
      - run:
          name: test API
          command:
            # each step runs in its own shell and venv activate does
            # does not persist.
            >-
            .\venv\Scripts\activate &&
            python -m pytest
            -s --assert=plain
            --cov-report term-missing
            --cov=machin
            -k "not full_train"
            -o junit_family=xunit1
            --junitxml test_results\test_api.xml
            --cov-report xml:test_results\cov_report.xml
            --html=test_results\test_api.html
            --self-contained-html
            .\test\
      - store_artifacts:
          path: test_results\test_api.xml
      - store_test_results:
          path: test_results\

workflows:
  main:
    jobs:
      - win-test
